# *************************************************************************************
# Plot demo on the results made from OzoneAnalysis_datatable.R
#
# 2015-07-12 - Tri.Nguyen
# 2015-09-26 - add Plot #3 (dot plot on Canada map background)
# *************************************************************************************

library(ggplot2)
require(ggmap) # install.packages("ggmap")
library(readr) # install.packages("readr")

#--------------------------------------------------------------------
# PLOT #1 (2 separate plots)
# Top 10 Cities in Canada, Average vs Max Yearly Ozone Level
#--------------------------------------------------------------------

dtPlot1 <- dtPollutedCities[1:10, .(Ranking=1:10, CityName, YearAvgOzone, YearMaxOzone)]

g1 <- ggplot(dtPlot1, aes(x=reorder(CityName, -Ranking), y=YearAvgOzone, fill=CityName)) +
	labs(title="Top 10 in Canada by Average Ozone Level", y="Average Ozone (2012)") +
	theme(plot.title=element_text(color="blue3", size=rel(1.2), face="bold"), axis.title.y=element_blank()) +
	geom_bar(stat="identity", alpha=0.75) +
	coord_flip() +
	geom_text(aes(label=round(YearAvgOzone,2), vjust=0.5, hjust=1.5), size=4, fontface="bold") +
	scale_fill_brewer(palette="Paired", guide=FALSE) +
	theme(axis.text.x = element_text(color="black", size=rel(1.2), face="bold"),
			axis.title.x = element_text(color="blue3", size=rel(1.2), face="bold"),
			axis.text.y = element_text(color="black", size=rel(1.2), face="bold"))


g2 <- ggplot(dtPollutedCities, aes(x=YearAvgOzone)) +
	labs(title="Average Ozone Distribution, Canada, 2012", x="Average Ozone") +
	theme(plot.title=element_text(color="blue3", size=rel(1.2), face="bold")) +
	geom_bar(stat="bin", alpha=0.5, fill="burlywood4", color="burlywood4", size=1) +
	theme(axis.text.x = element_text(color="black", size=rel(1.2), face="bold"),
			axis.title.x = element_text(color="blue3", size=rel(1.2), face="bold"),
			axis.text.y = element_text(color="black", size=rel(1.2), face="bold"),
			axis.title.y = element_text(color="blue3", size=rel(1.2), face="bold"))

# g2 <- ggplot(dtPlot1, aes(x=reorder(CityName, -Ranking), y=YearMaxOzone, fill=CityName)) +
# 	labs(title="Corresponding Max Ozone Level", y="Ozone (2012)") +
# 	theme(plot.title=element_text(color="blue3", size=rel(1.2), face="bold"), axis.title.y=element_blank()) +
# 	geom_bar(stat="identity", alpha=0.75) +
# 	coord_flip() +
# 	geom_text(aes(label=round(YearMaxOzone,2), vjust=0.5, hjust=1.5), size=4, fontface="bold") +
# 	scale_fill_brewer(palette="Paired", guide=FALSE) +
# 	theme(axis.text.x = element_text(color="black", size=rel(1.2), face="bold"),
# 			axis.text.y = element_text(color="black", size=rel(1.2), face="bold"))


gridExtra::grid.arrange(g1, g2, nrow=1, ncol=2)



#--------------------------------------------------------------------
# PLOT #2 (side by side bar graph)
# Top 10 Cities in Canada, Average vs Max Yearly Ozone Level
#--------------------------------------------------------------------

dtPlot2 <- dtPollutedCities[1:10, .(CityName=paste0(sprintf("%02d", 1:10), " (", CityName, ")"), YearAvgOzone, YearMaxOzone)]

ggplot(reshape2::melt(dtPlot2, id="CityName", variable.name="O3Measure"),
		 aes(x=CityName, y=value, fill=O3Measure)) +
	labs(title="Top 10 Cities in Canada, Average vs Max Yearly Ozone Level", y="Ozone (2012)") +
	theme(plot.title=element_text(color="blue3", size=rel(1.2), face="bold"), axis.title.x=element_blank()) +
	geom_bar(stat="identity", position="dodge", alpha=0.7) +
	scale_fill_manual(values=c("dodgerblue3", "burlywood4"), labels=c("Year AVG Ozone", "Year MAX Ozone")) +
	guides(fill=guide_legend(title=NULL)) + # Legends: remove title
	theme(legend.position = c(1,1), legend.justification = c(1,1),
			legend.text = element_text(face="bold", size=10),
			legend.background = element_rect(fill=FALSE, color="grey50", linetype=1)) +	
	theme(axis.text.x = element_text(angle=36, hjust=1, vjust=1, color="black", size=rel(1.2), face="bold"),
			axis.text.y = element_text(color="black", size=rel(1.2), face="bold"))


#--------------------------------------------------------------------
# PLOT #3 Draw on a Map. The Ozone value is plotted at the Lat/Long of the City
# The size and color of the dot represents the level of pollution
#--------------------------------------------------------------------

# re-read CSV (Ozone by Cities with Lat/Long already resolved)
# (NOTE: the CSV is generated by the utility section at the bottom of this script)
dfMapOzone <- readr::read_csv(file="~/Documents/IntelliJProjects/UG/HadoopLab/AirQualityAnalysis/src/main/R/OzoneByCities_withLatLong.csv",
	skip=1,
	col_names = c("Rank", "Province", "CityName", "YearAvgOzone", "YearMaxOzone", "Latitude", "Longitude"),
	col_types = "iccdidd")

ggplot() + ggplot2::borders(database="world", regions="Canada", col="gray30", fill="gray60") +
	labs(title="Average Ozone Level in Canada (2012)") +
	theme(plot.title=element_text(color="blue3", size=rel(1.2), face="bold")) +
	geom_point(data = dfMapOzone,
				  aes(x = Longitude, y = Latitude, color = YearAvgOzone, size = YearAvgOzone)) +
	scale_color_gradient(low = "yellow", high = "red") +
	theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank())



#--------------------------------------------------------------------
# Adding Lat/Long in dtPollutedCities + save on CSV
#--------------------------------------------------------------------
# Fix some cities names
cleanCityNames <- dtPollutedCities$CityName %>%
	gsub("Saint-Fran\xc7Ois", "Saint-Francois", ., ignore.case=TRUE) %>%
	gsub("Exp. Lakes Area", "Experimental Lakes Area", ., ignore.case=TRUE) %>%
	gsub("Nat. ", "National ", ., ignore.case=TRUE) %>%
	gsub("Metro Van\\s*-\\s*" , "", ., ignore.case=TRUE)

# Geocode the Lat/Long of the Cities
system.time(llCities <- ggmap::geocode(paste(cleanCityNames, dtPollutedCities$Province, "Canada", sep=","), source = "google"))
#    user  system elapsed
#   0.691   0.416  51.007


# Enrich dtPollutedCities with LatLong
dtPollutedCitiesLL <- cbind(dtPollutedCities, llCities)
setnames(dtPollutedCitiesLL, c("lon", "lat"), c("Longitude", "Latitude"))

# Save on File (re-use Lat/Long offline without live Geocoding)
write.table(dtPollutedCitiesLL[, .(Province, CityName, YearAvgOzone = round(YearAvgOzone,2), YearMaxOzone = round(YearMaxOzone,0), Latitude, Longitude)],
	file="./OzoneByCities_withLatLong.csv", col.names=TRUE, row.names=TRUE, quote=FALSE, sep=",")


# --- (end) ----
